server:
  port: 8020

spring:
  datasource:
    url: jdbc:jtds:sqlserver://localhost;databaseName=Eng_Soft_3
    username: root
    password: root
    driverClassName: net.sourceforge.jtds.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl