server:
  port: 8020

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/siscom?verifyServerCertificate=false&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver